{% set version = "1.1-1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-binom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/binom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/binom/binom_{{ version }}.tar.gz
  sha256: ee215f41223bb1ca80f91f54b99dc75339aac74906db57698e7c2b0d9a86befb

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('binom')"           # [not win]
    - "\"%R%\" -e \"library('binom')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=binom
  license: GPL-2.0-or-later
  summary: Constructs confidence intervals on the probability of success in a binomial experiment via several parameterizations
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
