appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: J/QfgULzdvnN02whBTZbE0NEu/7GtTRVTMiws99m1y8L5wUi/fVmT5B9HYM9nKc4V22b/BayBkZLEt1zLNZ6NfAVeOS7Vzq3Qxy2rcuiWsOWOa8DSRC1lOaMeh59+mKnfeZl/zRUjWVpIWcPBgsG5N5orLlS05bXOG4ZLtZSKC5JwIOoLBajOO5dGniDK39mgpf6vH0j9dOgnxEBeagOlzJ/9MLGON/dFMFpg0d/vuHrxRgOStd45F72Eb1VAssbkC26qdP1+pycPKXpDF8iQwetM5A4LLplZYvvwdR0zu8U3MavI8LMfTIwqzgtJqDuBtt05pnuOnt/EZvjdMUHzIPRH4ltDlgUGhMm3tTfPNu4RmAda/TAsMF/5i7IOXR3p13bPaz6wUkUcNQCjtRMv5Kam/FFvNvlqJGfWMM3Dg4cCVNDIgAY5okT5ZRB5eQ5S8dipYUW3ckKvIaGWzXS7ownp/IF8jtA4tYdp3+Z7vKCTZe+gWZVb/bd2n9dEkiHRijn0dkiU9hUqXIiGrm/mqplgJS682HadH8hkYpSbqirudKHCQFAC+MIOpOEjr4Ajt0y2I1k/ryyb1HNXPHekYKDWZ0Kye7IljQf51JwfA+EVtIcMbnlLQxT55fMYisptWJDc/bWUBb6k79AInf4KFh+LYD2soA/56J4GCDUZ70=
conda_forge_output_validation: true
